
rank-processor:
  timeout: 100
  pagesize: 3
  feed: "feed_"
server:
  port: 8099
  tomcat:
    max-threads: 500
    max-connections: 2048

swagger:
  enable: true
  packageScan: producer.controller
  title: ${spring.application.name}
  version: 1.0



management:
  health:
    redis:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.cloud.consul: DEBUG

cache:
  expire-after-write-seconds: 3
  init-capacity: 256000
  max-capacity: 256000

okhttp:
  pool:
    read-timeout: 200
    write-timeout: 200
    connect-timeout: 50
    max-idle: 100

redis:
  doc-materiel:
    database: 0
    timeout: 1000
    pool:
      max-idle: 50
      min-idle: 10
      max-total: 128
      max-wait: 60
    cluster:
      nodes: 10.200.128.189:6930,10.200.128.189:6931  # test env

