
rank-processor:
  timeout: 100
  pagesize: 3
  feed: "feed_"
server:
  port: 8099

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false
  health:
    redis:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.cloud.consul: DEBUG

cache:
  expire-after-write-seconds: 3
  init-capacity: 1024000
  max-capacity: 1024000

okhttp:
  pool:
    read-timeout: 200
    write-timeout: 200
    connect-timeout: 50
    max-idle: 100

redis:
  doc-materiel:
    database: 0
    timeout: 30
    pool:
      max-idle: 10
      min-idle: 1
      max-total: 64
      max-wait: 30
    cluster:
      nodes: 10.200.128.178:6108,10.200.128.177:6102,10.200.128.178:6107,10.200.128.175:6101,\
            10.200.128.179:6107,10.200.128.175:6102,10.200.128.177:6104
